### ISSUE TITLE
动画的组件现在还不可以用吗？？

### ISSUE THREAD

**Issue by sayll** [RubyLouvre/mmAnimate#5]
mmAnimate.js:765       Uncaught ReferenceError: Tween is not defined

**Comment by RubyLouvre** [comment]
帮我修一下，估计使用webpack划分模块时，一些模块没有引进来

**Comment by sayll** [comment]
前辈，高估我了。 T T才开始用webpack1个来月，这个真做不到

**Comment by FlyingCrow** [comment]
大神，今天打算集成进去mmAnimate，发现和上面这位仁兄的问题是一样的，我看了一下是在compact.js这个模块中require('updateColor')，这里的直接注释调就可以，而在updateColor这个模块中直接使用了Tween，所以把这里prototype中的uploadColor方法拿到Tween.js中去就可以了，打算提交一下的，可是告诉我我没有权限提交到git。。。所以在这儿说一下了。但是还没有正式使用，所以只是修改的不报错了。至于能不能用正在尝试😀

[update.zip](https://github.com/RubyLouvre/mmAnimate/files/490253/update.zip)

**Comment by RubyLouvre** [comment]
你要fork一下，然后 pull request
